back/config/routes.rb
Rails.application.routes.draw do
  resources :quests
  resources :game
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

back/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

back/app/models/quest.rb
class Quest < ApplicationRecord

  def options_array
    self.options.split(';') unless self.options.blank?
  end
end

back/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

back/app/controllers/game_controller.rb
class GameController < ApplicationController

  def index
    @quest = Quest.all.sample
  end

end

back/app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  before_action :set_quest, only: [:show, :edit, :update, :destroy]

  # GET /quests
  # GET /quests.json
  def index
    @quests = Quest.all
  end

  # GET /quests/1
  # GET /quests/1.json
  def show
  end

  # GET /quests/new
  def new
    @quest = Quest.new
  end

  # GET /quests/1/edit
  def edit
  end

  # POST /quests
  # POST /quests.json
  def create
    @quest = Quest.new(quest_params)

    respond_to do |format|
      if @quest.save
        format.html { redirect_to @quest, notice: 'Quest was successfully created.' }
        format.json { render :show, status: :created, location: @quest }
      else
        format.html { render :new }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quests/1
  # PATCH/PUT /quests/1.json
  def update
    respond_to do |format|
      if @quest.update(quest_params)
        format.html { redirect_to @quest, notice: 'Quest was successfully updated.' }
        format.json { render :show, status: :ok, location: @quest }
      else
        format.html { render :edit }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quests/1
  # DELETE /quests/1.json
  def destroy
    @quest.destroy
    respond_to do |format|
      format.html { redirect_to quests_url, notice: 'Quest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quest
      @quest = Quest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quest_params
      params.require(:quest).permit(:question, :options, :answer_idx)
    end
end

back/app/helpers/application_helper.rb
module ApplicationHelper
end

back/app/helpers/game_helper.rb
module GameHelper
end

back/app/helpers/quests_helper.rb
module QuestsHelper
end

back/app/views/game/index.html.erb
<h1><%= @quest.question %></h1>

<div>
  <% @quest.options.split(';').each_with_index do |opt, idx| %>
    <label>
      <%= radio_button_tag :selected_opt, idx %> <%= opt %>
    </label>
  <% end %>
  <%= button_tag "Answer", type: "button", id: 'ans_btn' %>

  <h2 id="correct" style="display:none">CORRECT!</h2>
  <h2 id="wrong" style="display:none">not this time! :(</h2>
</div>

<script lang="text/javascript">
  var answer_idx = parseInt(<%= @quest.answer_idx %>)
  $('#ans_btn').on('click', function() {
    let user_ans = $('input[type=radio]:checked').val();
    if(user_ans && user_ans == answer_idx) {
      $('#correct').css('display:block');
      console.log('bla')
    }
  })
</script>

back/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lyricspop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

back/app/views/quests/_form.html.erb
<%= form_with(model: quest, local: true) do |form| %>
  <% if quest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quest.errors.count, "error") %> prohibited this quest from being saved:</h2>

      <ul>
      <% quest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question %>
    <%= form.text_field :question %>
  </div>

  <div class="field">
    <%= form.label :options %>
    <%= form.text_field :options %>
  </div>

  <div class="field">
    <%= form.label :answer_idx %>
    <%= form.number_field :answer_idx %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

back/app/views/quests/edit.html.erb
<h1>Editing Quest</h1>

<%= render 'form', quest: @quest %>

<%= link_to 'Show', @quest %> |
<%= link_to 'Back', quests_path %>

back/app/views/quests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quests</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Options</th>
      <th>Answer idx</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quests.each do |quest| %>
      <tr>
        <td><%= quest.question %></td>
        <td><%= quest.options %></td>
        <td><%= quest.answer_idx %></td>
        <td><%= link_to 'Show', quest %></td>
        <td><%= link_to 'Edit', edit_quest_path(quest) %></td>
        <td><%= link_to 'Destroy', quest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quest', new_quest_path %>

back/app/views/quests/new.html.erb
<h1>New Quest</h1>

<%= render 'form', quest: @quest %>

<%= link_to 'Back', quests_path %>

back/app/views/quests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @quest.question %>
</p>

<p>
  <strong>Options:</strong>
  <%= @quest.options %>
</p>

<p>
  <strong>Answer idx:</strong>
  <%= @quest.answer_idx %>
</p>

<%= link_to 'Edit', edit_quest_path(@quest) %> |
<%= link_to 'Back', quests_path %>